#!/usr/bin/env python3

import sys
import os
sys.path.append('ai-integration/policy-generator')

from bedrock_policy_generator import BedrockPolicyGenerator
import json

def test_bedrock_policy_generator():
    """Test Bedrock policy generation"""
    
    print("🤖 Testing Bedrock Policy Generator...")
    
    try:
        generator = BedrockPolicyGenerator()
        
        # Test policy generation
        print("\n📋 Generating policy for data scientist role...")
        
        policy_result = generator.generate_policy_from_description(
            "Data scientist needs S3 access for ML training data and SageMaker for model training",
            "data-scientist"
        )
        
        print("✅ Policy generated successfully!")
        print(f"Role: {policy_result['role_type']}")
        print(f"Generated by: {policy_result['generated_by']}")
        
        # Save the generated policy
        with open('generated_policy_example.json', 'w') as f:
            json.dump(policy_result, f, indent=2)
        
        print("💾 Policy saved to generated_policy_example.json")
        
        # Test risk analysis
        print("\n🔍 Analyzing policy risks...")
        risks = generator.analyze_policy_risks(policy_result['policy'])
        
        print(f"Risk analysis completed: {len(risks)} potential issues identified")
        
        return True
        
    except Exception as e:
        print(f"❌ Error testing Bedrock: {e}")
        print("💡 Make sure:")
        print("   - AWS credentials are configured (aws configure)")
        print("   - Bedrock is enabled in your AWS account")
        print("   - You have access to Claude model")
        return False

def test_enterprise_iam_manager():
    """Test the enterprise IAM manager"""
    
    print("\n🏢 Testing Enterprise IAM Manager...")
    
    try:
        sys.path.append('automation/aws')
        from enterprise_iam_manager import EnterpriseIAMManager
        
        manager = EnterpriseIAMManager(environment='dev')
        print("✅ Enterprise IAM Manager initialized successfully!")
        
        # Test CSV processing (dry run)
        if os.path.exists('enterprise_users.csv'):
            print("📊 Found enterprise_users.csv - ready for processing")
            print("💡 Run: manager.process_user_requests('enterprise_users.csv')")
        else:
            print("⚠️ enterprise_users.csv not found")
        
        return True
        
    except Exception as e:
        print(f"❌ Error testing Enterprise IAM Manager: {e}")
        return False

if __name__ == "__main__":
    print("🚀 Starting AI Integration Tests...\n")
    
    # Test 1: Bedrock Policy Generator
    bedrock_success = test_bedrock_policy_generator()
    
    # Test 2: Enterprise IAM Manager
    iam_success = test_enterprise_iam_manager()
    
    print(f"\n📊 Test Results:")
    print(f"   Bedrock Policy Generator: {'✅ PASS' if bedrock_success else '❌ FAIL'}")
    print(f"   Enterprise IAM Manager: {'✅ PASS' if iam_success else '❌ FAIL'}")
    
    if bedrock_success and iam_success:
        print("\n🎉 All core components are working!")
        print("🔄 Next: Configure AWS credentials and test with real data")
    else:
        print("\n⚠️ Some components need configuration")
        print("💡 Check AWS credentials and permissions")
